services:
  hospital1:
    build:
      context: .
      dockerfile: hospital_1/Dockerfile
    container_name: hospital_1_server
    ports:
      - "8001:8001"
    restart: unless-stopped

  hospital2:
    build:
      context: .
      dockerfile: hospital_2/Dockerfile
    container_name: hospital_2_server
    ports:
      - "8002:8002"
    restart: unless-stopped
