services:
  employability1:
    build:
      context: .
      dockerfile: employability_1/Dockerfile
    container_name: employability_1_server
    ports:
      - "8001:8001"
    restart: unless-stopped

  employability2:
    build:
      context: .
      dockerfile: employability_2/Dockerfile
    container_name: employability_2_server
    ports:
      - "8002:8002"
    restart: unless-stopped

